import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';

const root = fileURLToPath(new URL('../', import.meta.url));
const palette = (token) => Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(shade => [shade, `var(${token})`]));
const slate = {
  50: 'var(--bg-page)', 100: 'var(--bg-raised)', 200: 'var(--line-hairline)',
  300: 'var(--line-strong)', 400: 'var(--text-muted)', 500: 'var(--text-secondary)',
  600: 'var(--text-secondary)', 700: 'var(--text-primary)', 800: 'var(--text-primary)', 900: 'var(--text-primary)',
};
const tone = (name) => Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(shade => [shade,
  `rgb(var(--delta-${name}-${shade <= 100 ? 'soft' : shade <= 300 ? 'line' : 'ink'}) / <alpha-value>)`]));
const accent = tone('accent');
const status = tone;
const generated = await postcss([tailwindcss({
  content: [path.join(root, 'components/tools/gradify/delta/**/*.{ts,tsx}')],
  important: '#gradify-delta',
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: { slate, gray:slate, white:'var(--bg-surface)', indigo:accent, purple:accent, violet:accent, amber:status('warn'), yellow:status('warn'), blue:status('info'), sky:status('info'), emerald:status('ok'), green:status('ok'), red:status('alert'), rose:status('alert'), orange:status('warn'), cyan:status('info'), fuchsia:accent },
      fontFamily: { sans:['var(--font-sans)'], mono:['var(--font-mono)'] },
      borderRadius: { lg:'var(--r-1)', xl:'var(--r-2)', '2xl':'var(--r-2)', '3xl':'var(--r-2)' },
      boxShadow: { sm:'none', DEFAULT:'none', md:'none', lg:'none', xl:'none', '2xl':'none' },
      fontSize: { xs:['0.8125rem','1.5'], sm:['0.875rem','1.5'] },
    },
  },
})]).process('@tailwind utilities;', { from:undefined });
// Scope Tailwind's generated variable reset too; it must not affect other tools.
const scoped = postcss.parse(generated.css);
scoped.walkRules(rule => {
  if (rule.parent?.type === 'atrule' && rule.parent.name.endsWith('keyframes')) return;
  if (!rule.selector.includes('#gradify-delta')) rule.selector = rule.selector.split(',').map(selector => `#gradify-delta ${selector.trim()}`).join(', ');
});
const output = path.join(root,'components/tools/gradify/delta.generated.css');
await mkdir(path.dirname(output), {recursive:true});
await writeFile(output, '/* Generated by npm run prepare:gradify. Scoped Gradify presentation. */\n' + scoped.toString());
await mkdir(path.join(root,'public/vendor/gradify'), {recursive:true});
await copyFile(path.join(root,'node_modules/pdfjs-dist/build/pdf.worker.min.mjs'),path.join(root,'public/vendor/gradify/pdf.worker.min.mjs'));
const pkg = JSON.parse(await readFile(path.join(root,'node_modules/pdfjs-dist/package.json'),'utf8'));
await writeFile(path.join(root,'public/vendor/gradify/README.txt'), `PDF.js worker ${pkg.version}, copied from the installed pdfjs-dist dependency. Mozilla / Apache-2.0. Regenerate using npm run prepare:gradify.\n`);
await copyFile(path.join(root,'node_modules/pdfjs-dist/LICENSE'),path.join(root,'public/vendor/gradify/LICENSE'));
console.log('Prepared scoped Gradify styles and local PDF.js worker.');
